export const books = [
  {
    id: 1,
    title: "The Rust Programming Language (Covers Rust 2018)",
    author: "Steve Klabnik, Carol Nichols",
    publisher: "No Starch Press",
    genre: "Computers",
    isbnNo: 9781718500457,
    numofPages: 561,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 2,
    title: "Introduction to Programming Languages",
    author: "Arvind Kumar Bansal",
    publisher: "CRC Press",
    genre: "Computers",
    isbnNo: 9781466565159,
    numofPages: 624,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 3,
    title: "COMPUTER PROGRAMMING IN C, SECOND EDITION",
    author: "RAJARAMAN, V.",
    publisher: "PHI Learning Pvt. Ltd.",
    genre: "Computers",
    isbnNo: 9789388028349,
    numofPages: 388,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 4,
    title: "Python Programming in Context",
    author: "Bradley N. Miller, David L. Ranum, Julie Anderson",
    publisher: "Jones & Bartlett Learning",
    genre: "Computers",
    isbnNo: 9781284175554,
    numofPages: 516,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 5,
    title: "Core Python Programming",
    author: "Wesley Chun",
    publisher: "Prentice Hall Professional",
    genre: "Computers",
    isbnNo: 9780130260369,
    numofPages: 805,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 6,
    title: "Learn to Code by Solving Problems",
    author: "Daniel Zingaro",
    publisher: "No Starch Press",
    genre: "Computers",
    isbnNo: 9781718501331,
    numofPages: 392,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 7,
    title: "Programming Language Concepts",
    author: "Carlo Ghezzi, Mehdi Jazayeri",
    publisher: "John Wiley & Sons",
    genre: "Computers",
    isbnNo: "",
    numofPages: 456,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 8,
    title: "Elements of Programming",
    author: "Alexander Stepanov, Paul McJones",
    publisher: "Lulu.com",
    genre: "Computers",
    isbnNo: 9780578222141,
    numofPages: 282,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 9,
    title: "Learning to Program",
    author: "Steven Foote",
    publisher: "Addison-Wesley Professional",
    genre: "Computers",
    isbnNo: 9780133795226,
    numofPages: 336,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 10,
    title: "Guide to Competitive Programming",
    author: "Antti Laaksonen",
    publisher: "Springer",
    genre: "Computers",
    isbnNo: 9783319725475,
    numofPages: 283,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 11,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    publisher: "Addison-Wesley Professional",
    genre: "Computers",
    isbnNo: 9780132119177,
    numofPages: 346,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 12,
    title: "The Pragmatic Programmer",
    author: "David Thomas, Andrew Hunt",
    publisher: "Addison-Wesley Professional",
    genre: "Computers",
    isbnNo: 9780135956915,
    numofPages: 390,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 13,
    title: "Data-Oriented Programming",
    author: "Yehonathan Sharvit",
    publisher: "Simon and Schuster",
    genre: "Computers",
    isbnNo: 9781617298578,
    numofPages: 422,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 14,
    title: "A Book on C",
    author: "Al Kelley, Ira Pohl",
    publisher: "Benjamin-Cummings Publishing Company",
    genre: "Computers",
    isbnNo: 9780805300604,
    numofPages: 548,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 15,
    title: "Getting Inside Java - Beginners Guide",
    author: "Prem Kumar",
    publisher: "Pencil",
    genre: "Computers",
    isbnNo: 9789354386459,
    numofPages: 208,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 16,
    title: "Programming in C",
    author: "Ashok N. Kamthane",
    publisher: "",
    genre: "C (Computer program language)",
    isbnNo: 9789380856421,
    numofPages: 657,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 17,
    title: "Programming Fundamentals",
    author: "Kenneth Leroy Busbee",
    publisher: "",
    genre: "Computers",
    isbnNo: 9789888407491,
    numofPages: 340,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 18,
    title: "COMPUTER PROGRAMMING IN FORTRAN 77",
    author: "V. RAJARAMAN",
    publisher: "PHI Learning Pvt. Ltd.",
    genre: "Computers",
    isbnNo: 9788120311725,
    numofPages: 212,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 19,
    title: "Elements of Programming",
    author: "Alexander A. Stepanov, Paul McJones",
    publisher: "Addison-Wesley Professional",
    genre: "Computers",
    isbnNo: 9780321635372,
    numofPages: 279,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 20,
    title: "Programming in Lua",
    author: "Roberto Ierusalimschy",
    publisher: "Roberto Ierusalimschy",
    genre: "Computers",
    isbnNo: 9788590379829,
    numofPages: 329,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 21,
    title: "Programming Persistent Memory",
    author: "Steve Scargall",
    publisher: "Apress",
    genre: "Computers",
    isbnNo: 9781484249321,
    numofPages: 384,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 22,
    title: "Programming Problems",
    author: "B. Green",
    publisher: "Createspace Independent Pub",
    genre: "Computers",
    isbnNo: 9781475071962,
    numofPages: 156,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 23,
    title: "Expert Python Programming",
    author: "Michał Jaworski, Tarek Ziadé",
    publisher: "Packt Publishing Ltd",
    genre: "Computers",
    isbnNo: 9781801076197,
    numofPages: 631,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 24,
    title: "Practical Goal Programming",
    author: "Dylan Jones, Mehrdad Tamiz",
    publisher: "Springer Science & Business Media",
    genre: "Business & Economics",
    isbnNo: 9781441957719,
    numofPages: 180,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 25,
    title: "Fundamentals of Computer Programming with C#",
    author: "Svetlin Nakov, Veselin Kolev",
    publisher: "Faber Publishing",
    genre: "Computers",
    isbnNo: 9789544007737,
    numofPages: 1132,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 26,
    title: "Code",
    author: "Charles Petzold",
    publisher: "Microsoft Press",
    genre: "Computers",
    isbnNo: 9780137909292,
    numofPages: 562,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 27,
    title: "Programming in Python 3",
    author: "Mark Summerfield",
    publisher: "Pearson Education",
    genre: "Computers",
    isbnNo: 9780321606594,
    numofPages: 552,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 28,
    title: "Programming In C: A Practical Approach",
    author: "Ajay Mittal",
    publisher: "Pearson Education India",
    genre: "C (Computer program language)",
    isbnNo: 9788131729342,
    numofPages: 768,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 29,
    title: "The C++ Programming Language",
    author: "Bjarne Stroustrup",
    publisher: "Pearson Education India",
    genre: "C++ (Computer program language)",
    isbnNo: 9788131705216,
    numofPages: 1034,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 30,
    title: "Practical C++ Programming",
    author: "Steve Oualline",
    publisher: "O'Reilly Media, Inc.",
    genre: "Computers",
    isbnNo: 9781449367169,
    numofPages: 576,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 31,
    title: "Programming Erlang",
    author: "Joe Armstrong",
    publisher: "Pragmatic Bookshelf",
    genre: "Computers",
    isbnNo: 9781680504323,
    numofPages: 755,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 32,
    title: "Programming in Modula-3",
    author: "Laszlo Böszörmenyi, Carsten Weich",
    publisher: "Springer",
    genre: "Computers",
    isbnNo: 9783642646140,
    numofPages: 571,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 33,
    title: "The History Book",
    author: "DK",
    publisher: "Dorling Kindersley Ltd",
    genre: "History",
    isbnNo: 9780241282229,
    numofPages: 354,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 34,
    title: "The Lessons of History",
    author: "Will Durant, Ariel Durant",
    publisher: "Simon and Schuster",
    genre: "History",
    isbnNo: 9781439170199,
    numofPages: 128,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 35,
    title: "The History Book",
    author: "Dorling Kindersley Publishing Staff",
    publisher: "",
    genre: "History",
    isbnNo: 9780241225929,
    numofPages: 0,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 36,
    title: "A Companion to the History of the Book",
    author: "Simon Eliot, Jonathan Rose",
    publisher: "John Wiley & Sons",
    genre: "Literary Criticism",
    isbnNo: 9781444356588,
    numofPages: 617,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 37,
    title: "The American College and University",
    author: "Frederick Rudolph",
    publisher: "University of Georgia Press",
    genre: "Education",
    isbnNo: 9780820312842,
    numofPages: 592,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 38,
    title: "That's Not in My American History Book",
    author: "Thomas Ayres",
    publisher: "Taylor Trade Publications",
    genre: "United States",
    isbnNo: 9781589791077,
    numofPages: 257,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 39,
    title: "An Introduction to Book History",
    author: "David Finkelstein, Alistair McCleery",
    publisher: "Routledge",
    genre: "Social Science",
    isbnNo: 9781134380060,
    numofPages: 167,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 40,
    title: "The Little Book of History",
    author: "DK",
    publisher: "Dorling Kindersley Ltd",
    genre: "History",
    isbnNo: 9780241547489,
    numofPages: 503,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 41,
    title: "End of History and the Last Man",
    author: "Francis Fukuyama",
    publisher: "Simon and Schuster",
    genre: "History",
    isbnNo: 9781416531784,
    numofPages: 464,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 42,
    title: "The Cambridge Companion to the History of the Book",
    author: "Leslie Howsam",
    publisher: "Cambridge University Press",
    genre: "Language Arts & Disciplines",
    isbnNo: 9781107023734,
    numofPages: 301,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 43,
    title: "A Little History of the World",
    author: "E. H. Gombrich",
    publisher: "Yale University Press",
    genre: "History",
    isbnNo: 9780300213973,
    numofPages: 401,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 44,
    title: "The History Book (Miles Kelly).",
    author:
      "MAKE BELIEVE IDEAS LTD. MAKE BELIEVE IDEAS LTD, Simon Adams, Philip Steele, Stewart Ross, Richard Platt",
    publisher: "",
    genre: "World history",
    isbnNo: 9781805443407,
    numofPages: 0,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 45,
    title: "Encyclopedia of Local History",
    author: "Carol Kammen, Amy H. Wilson",
    publisher: "Rowman & Littlefield Publishers",
    genre: "United States",
    isbnNo: 9780759120488,
    numofPages: 0,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 46,
    title: "History at the Limit of World-History",
    author: "Ranajit Guha",
    publisher: "Columbia University Press",
    genre: "History",
    isbnNo: 9780231505093,
    numofPages: 156,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 47,
    title: "A World at Arms",
    author: "Gerhard L. Weinberg",
    publisher: "Cambridge University Press",
    genre: "History",
    isbnNo: 9780521618267,
    numofPages: 1216,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 48,
    title: "Quirky History",
    author: "Mini Menon",
    publisher: "Harper Collins",
    genre: "Juvenile Nonfiction",
    isbnNo: 9789353578800,
    numofPages: 184,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 49,
    title: "A History of Modern India, 1480-1950",
    author: "Claude Markovits",
    publisher: "Anthem Press",
    genre: "History",
    isbnNo: 9781843311522,
    numofPages: 617,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 50,
    title: "Rethinking History",
    author: "Keith Jenkins",
    publisher: "Routledge",
    genre: "History",
    isbnNo: 9781134408283,
    numofPages: 116,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 51,
    title: "A History of History",
    author: "Alun Munslow",
    publisher: "Routledge",
    genre: "History",
    isbnNo: 9780415677141,
    numofPages: 236,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 52,
    title: "A History of India",
    author: "Hermann Kulke, Dietmar Rothermund",
    publisher: "Psychology Press",
    genre: "India",
    isbnNo: 9780415154826,
    numofPages: 406,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 53,
    title: "An Introduction to Book History",
    author: "David Finkelstein, Alistair McCleery",
    publisher: "Routledge",
    genre: "Design",
    isbnNo: 9780415688055,
    numofPages: 178,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 54,
    title: "What Is History, Now?",
    author: "Suzannah Lipscomb, Helen Carr",
    publisher: "Hachette UK",
    genre: "History",
    isbnNo: 9781474622486,
    numofPages: 285,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 55,
    title: "The Oxford Illustrated History of the Book",
    author: "James Raven",
    publisher: "Oxford University Press",
    genre: "Crafts & Hobbies",
    isbnNo: 9780191007507,
    numofPages: 468,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 56,
    title: "A Textbook of Historiography, 500 B.C. to A.D. 2000",
    author: "E. Sreedharan",
    publisher: "Orient Blackswan",
    genre: "History",
    isbnNo: 9788125026570,
    numofPages: 600,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 57,
    title: "A Concise History of Greece",
    author: "Richard Clogg",
    publisher: "Cambridge University Press",
    genre: "History",
    isbnNo: 9780521004794,
    numofPages: 316,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 58,
    title: "Time and Power",
    author: "Christopher Clark",
    publisher: "Princeton University Press",
    genre: "History",
    isbnNo: 9780691217321,
    numofPages: 310,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 59,
    title: "International Law and the Politics of History",
    author: "Anne Orford",
    publisher: "Cambridge University Press",
    genre: "History",
    isbnNo: 9781108480949,
    numofPages: 395,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 60,
    title: "National Geographic History Book",
    author: "Marcus Cowper",
    publisher: "National Geographic Books",
    genre: "History",
    isbnNo: 9781426206795,
    numofPages: 188,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 61,
    title: "Search History",
    author: "Eugene Lim",
    publisher: "Coffee House Press",
    genre: "Fiction",
    isbnNo: 9781566896269,
    numofPages: 162,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 62,
    title: "A History of the Modern World",
    author: "Ranjan Chakrabarti",
    publisher: "Primus Books",
    genre: "History, Modern",
    isbnNo: 9789380607504,
    numofPages: 0,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 63,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    publisher: "Random House",
    genre: "History",
    isbnNo: 9781448190690,
    numofPages: 353,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 64,
    title: "The Past Before Us",
    author: "Romila Thapar",
    publisher: "Harvard University Press",
    genre: "History",
    isbnNo: 9780674726529,
    numofPages: 915,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 65,
    title: "History Education and Conflict Transformation",
    author: "Charis Psaltis, Mario Carretero, Sabina Čehajić-Clancy",
    publisher: "Springer",
    genre: "Education",
    isbnNo: 9783319546810,
    numofPages: 389,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 66,
    title: "The Calling of History",
    author: "Dipesh Chakrabarty",
    publisher: "University of Chicago Press",
    genre: "Biography & Autobiography",
    isbnNo: 9780226100456,
    numofPages: 315,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 67,
    title: "What is the History of the Book?",
    author: "James Raven",
    publisher: "John Wiley & Sons",
    genre: "History",
    isbnNo: 9781509523214,
    numofPages: 196,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 68,
    title: "Wise & Otherwise",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9788184759006,
    numofPages: 232,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 69,
    title: "The Tastiest Of All",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Juvenile Fiction",
    isbnNo: 9789351183594,
    numofPages: 12,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 70,
    title: "Grandma's Bag of Stories",
    author: "Sudha Murthy",
    publisher: "Puffin",
    genre: "Children's stories",
    isbnNo: 9780143333623,
    numofPages: 192,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 71,
    title: "The Seed of Truth",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183563,
    numofPages: 13,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 72,
    title: "The Day I Stopped Drinking Milk",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180555,
    numofPages: 14,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 73,
    title: "The Call",
    author: "Sudha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180715,
    numofPages: 10,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 74,
    title: "A Fair Deal",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183556,
    numofPages: 13,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 75,
    title: "Three Women, Three Ponds",
    author: "Sudha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180593,
    numofPages: 10,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 76,
    title: "Helping the Dead",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180586,
    numofPages: 0,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 77,
    title: "Genes",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180579,
    numofPages: 0,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 78,
    title: "A Woman's Ritual",
    author: "Sudha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180685,
    numofPages: 10,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 79,
    title: "The Gift of Sacrifice",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180630,
    numofPages: 0,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 80,
    title: "No Man’s Garden",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180609,
    numofPages: 0,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 81,
    title: "The Best Friend",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183693,
    numofPages: 13,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 82,
    title: "Hindu Mother, Muslim Son",
    author: "Sudha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180531,
    numofPages: 10,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 83,
    title: "The Selfish Groom",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183860,
    numofPages: 13,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 84,
    title: "Uncle Sam",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180708,
    numofPages: 0,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 85,
    title: "The Wise King",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183662,
    numofPages: 13,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 86,
    title: "Lazy Portado",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180692,
    numofPages: 0,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 87,
    title: "Miserable Success",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180678,
    numofPages: 0,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 88,
    title: "Good Luck, Gopal",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183709,
    numofPages: 14,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 89,
    title: "Do You Remember?",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180739,
    numofPages: 0,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 90,
    title: "Teen Hazar Tanke",
    author: "Sudha Murthy",
    publisher: "",
    genre: "Fiction",
    isbnNo: 9789352667437,
    numofPages: 178,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 91,
    title: "The Clever Brothers",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183761,
    numofPages: 12,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 92,
    title: "Sharing with a Ghost",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180654,
    numofPages: 0,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 93,
    title: "Sticky Bottoms",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180616,
    numofPages: 0,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 94,
    title: "Foot in the Mouth",
    author: "Suddha Murty",
    publisher: "Penguin UK",
    genre: "Literary Collections",
    isbnNo: 9789351180661,
    numofPages: 0,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 95,
    title: "MANADA MATU",
    author: "Smt. Sudha Murthy",
    publisher: "Sapna Book House (P) Ltd.",
    genre: "Authors, Kannada",
    isbnNo: 9788128004353,
    numofPages: 186,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 96,
    title: "Apna Deepak Swayam Banen",
    author: "Sudha Murty",
    publisher: "Prabhat Prakashan",
    genre: "Self-Help",
    isbnNo: 9788173155000,
    numofPages: 90,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 97,
    title: "Dollar Bahoo",
    author: "Sudha Murty",
    publisher: "Prabhat Prakashan",
    genre: "Fiction",
    isbnNo: 9788173153501,
    numofPages: 99,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 98,
    title:
      "Common Yet Uncommon (Hindi)/Sadharan Phir Bhi Asadharan/साधारण फिर भी असाधारण",
    author: "Sudha Murthy/सुधा मूर्ति",
    publisher: "Penguin Random House India Private Limited",
    genre: "Fiction",
    isbnNo: 9789357088961,
    numofPages: 181,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 99,
    title: "KANNADA : SAMANYARALLI ASAMANYARU",
    author: "Smt. Sudha Murthy",
    publisher: "Sapna Book House (P) Ltd.",
    genre: "Short stories, Kannada",
    isbnNo: 9788128005039,
    numofPages: 183,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 100,
    title: "Magic in the Air",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183853,
    numofPages: 14,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 101,
    title: "Emperor of Alakavati",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183730,
    numofPages: 17,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 102,
    title: "The Last Laddoo",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183587,
    numofPages: 13,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 103,
    title: "The White Crow",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183631,
    numofPages: 13,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 104,
    title: "The Magic Drum",
    author: "Sudha Murthy",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9789351183907,
    numofPages: 14,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 105,
    title: "Sita",
    author: "Amish Tripathi",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789356290945,
    numofPages: 333,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 106,
    title: "The Oath of the Vayuputras",
    author: "Amish Tripathi",
    publisher: "Hachette UK",
    genre: "Fiction",
    isbnNo: 9781780874104,
    numofPages: 400,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 107,
    title: "The Bachelor Dad",
    author: "Tusshar Kapoor",
    publisher: "Penguin Random House India Private Limited",
    genre: "Biography & Autobiography",
    isbnNo: 9789354924255,
    numofPages: 192,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 108,
    title: "Xx C. Top",
    author: "Vytenis Rozukas",
    publisher: "AuthorHouse",
    genre: "Fiction",
    isbnNo: 9781496976987,
    numofPages: 295,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 109,
    title: "The Nine-Chambered Heart",
    author: "Janice Pariat",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789352773800,
    numofPages: 216,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 110,
    title: "Ramayana Pack (4 Volumes)",
    author: "Shubha Vilas",
    publisher: "Jaico Publishing House",
    genre: "Self-Help",
    isbnNo: 9789386867650,
    numofPages: 1303,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 111,
    title: "The Secret Of The Nagas (Shiva Trilogy Book 2)",
    author: "Amish Tripathi",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789356290679,
    numofPages: 337,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 112,
    title: "Ancient Promises",
    author: "Jaishree Misra",
    publisher: "Penguin Books India",
    genre: "East Indians",
    isbnNo: 9780140293593,
    numofPages: 324,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 113,
    title: "Advances in Computer and Computational Sciences",
    author:
      "Sanjiv K. Bhatia, Krishn K. Mishra, Shailesh Tiwari, Vivek Kumar Singh",
    publisher: "Springer",
    genre: "Technology & Engineering",
    isbnNo: 9789811037733,
    numofPages: 713,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 114,
    title: "The Sialkot Saga",
    author: "Ashwin Sanghi",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789356292468,
    numofPages: 546,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 115,
    title: "Son of the Thundercloud",
    author: "Easterine Kire",
    publisher: "",
    genre: "Fiction",
    isbnNo: 9789386338143,
    numofPages: 152,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 116,
    title: "Fluid",
    author: "Ashish Jaiswal",
    publisher: "",
    genre: "Education",
    isbnNo: 9788183285278,
    numofPages: 256,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 117,
    title: "The Liberation of Sita",
    author: "Volga",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789352775026,
    numofPages: 128,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 118,
    title: "The Eternal World",
    author: "Christopher Farnsworth",
    publisher: "HarperCollins",
    genre: "Fiction",
    isbnNo: 9780062282934,
    numofPages: 365,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 119,
    title: "Keepers of the Kalachakra",
    author: "Ashwin Sanghi",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789356292482,
    numofPages: 374,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 120,
    title: "Digital Hinduism",
    author: "Xenia Zeiler",
    publisher: "Routledge",
    genre: "Religion",
    isbnNo: 9781351607322,
    numofPages: 304,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 121,
    title: "The Illuminated",
    author: "Anindita Ghose",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789354226182,
    numofPages: 234,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 122,
    title: "Boats on Land",
    author: "Janice Pariat",
    publisher: "Random House India",
    genre: "Fiction",
    isbnNo: 9788184003390,
    numofPages: 200,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 123,
    title: "Cuckold",
    author: "Kiran Nagarkar",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789351770107,
    numofPages: 633,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 124,
    title: "Stories We Never Tell",
    author: "Savi Sharma",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789356293304,
    numofPages: 204,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 125,
    title: "The Fisher Queen's Dynasty",
    author: "Kavita Kané",
    publisher: "Rupa Publ iCat Ions India",
    genre: "Fiction",
    isbnNo: 9789355208767,
    numofPages: 0,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 126,
    title: "Chander and Sudha",
    author: "Dharamvir Bharati",
    publisher: "Penguin UK",
    genre: "Fiction",
    isbnNo: 9788184750294,
    numofPages: 360,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 127,
    title: "Living with Merlin",
    author: "Anita Bakshi",
    publisher: "Partridge Publishing",
    genre: "Self-Help",
    isbnNo: 9781482840193,
    numofPages: 233,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 128,
    title: "Ramayana: The Game of Life – Book 2: Conquer Change",
    author: "Shubha Vilas",
    publisher: "Jaico Publishing House",
    genre: "Religion",
    isbnNo: 9789386348906,
    numofPages: 404,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 129,
    title: "Food Fights",
    author: "Charles C. Ludington, Matthew Morse Booker",
    publisher: "",
    genre: "Cooking",
    isbnNo: 9781469652894,
    numofPages: 304,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 130,
    title: "The Shape of Design",
    author: "Frank Chimero",
    publisher: "",
    genre: "Design",
    isbnNo: 9780985472207,
    numofPages: 131,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 131,
    title: "Everyone Has a Story",
    author: "Savi Sharma",
    publisher: "",
    genre: "Friendship",
    isbnNo: 9789386036759,
    numofPages: 0,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 132,
    title: "Go Kiss the World",
    author: "Subroto Bagchi",
    publisher: "Penguin Books India",
    genre: "Executives",
    isbnNo: 9780670082308,
    numofPages: 260,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 133,
    title: "Scion of Ikshvaku",
    author: "Amish, Amish Tripathi",
    publisher: "Westland Publication Limited",
    genre: "Hindu mythology",
    isbnNo: 9789385152146,
    numofPages: 0,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 134,
    title: "The Sand Fish",
    author: "Maha Gargash",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9780061959868,
    numofPages: 0,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 135,
    title: "2 States: The Story of My Marriage (Movie Tie-In Edition)",
    author: "Chetan Bhagat",
    publisher: "Rupa Publications",
    genre: "Fiction",
    isbnNo: 9788129132543,
    numofPages: 280,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 136,
    title: "The Woman on the Orient Express",
    author: "Lindsay Jayne Ashford",
    publisher: "Charnwood",
    genre: "Female friendship",
    isbnNo: 9781444836714,
    numofPages: 416,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 137,
    title: "Let's Talk Money",
    author: "Monika Halan",
    publisher: "Harper Collins",
    genre: "Business & Economics",
    isbnNo: 9789352779406,
    numofPages: 184,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 138,
    title: "Blind Faith",
    author: "Sagarika Ghose",
    publisher: "Harper Collins",
    genre: "Fiction",
    isbnNo: 9789351367994,
    numofPages: 188,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 139,
    title: "Dysmorphic Kingdom",
    author: "Colleen Chen",
    publisher: "",
    genre: "Fantasy fiction",
    isbnNo: 9781940233239,
    numofPages: 320,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 140,
    title: "Advice and Dissent",
    author: "Y.V. Reddy",
    publisher: "Harper Collins",
    genre: "Biography & Autobiography",
    isbnNo: 9789352643059,
    numofPages: 496,
    totalNumberOfCopies: 7,
    availableNumberOfCopies: 7,
  },
  {
    id: 141,
    title: "Angels & Demons",
    author: "Dan Brown",
    publisher: "Simon and Schuster",
    genre: "Fiction",
    isbnNo: 9780743493468,
    numofPages: 496,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 142,
    title: "Angels and Demons",
    author: "Dan Brown",
    publisher: "Corgi Books",
    genre: "Fiction",
    isbnNo: 9780552160896,
    numofPages: 0,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 143,
    title: "Angels & Demons",
    author: "Dan Brown",
    publisher: "Simon and Schuster",
    genre: "Anti-Catholicism",
    isbnNo: 9781416528654,
    numofPages: 8,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 144,
    title: "Angels & Demons Special Illustrated Edition",
    author: "Dan Brown",
    publisher: "Simon and Schuster",
    genre: "Fiction",
    isbnNo: 9780743277716,
    numofPages: 532,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 145,
    title: "Angels and Demons",
    author: "Dan Brown",
    publisher: "Random House",
    genre: "Anti-Catholicism",
    isbnNo: 9780552173469,
    numofPages: 642,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 146,
    title: "Angels and Demons",
    author: "Serge-Thomas Bonino",
    publisher: "CUA Press",
    genre: "Religion",
    isbnNo: 9780813227993,
    numofPages: 345,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 147,
    title: "Angels and Demons",
    author: "Peter Kreeft",
    publisher: "Ignatius Press",
    genre: "Religion",
    isbnNo: 9781681490380,
    numofPages: 164,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 148,
    title: "Angels and Demons",
    author: "Benny Hinn",
    publisher: "Benny Hinn Ministries",
    genre: "Religion",
    isbnNo: 9781590244593,
    numofPages: 208,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 149,
    title: "Dan Brown’s Robert Langdon Series",
    author: "Dan Brown",
    publisher: "Random House",
    genre: "Fiction",
    isbnNo: 9781473543201,
    numofPages: 2082,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 150,
    title: "The Mammoth Book of Angels & Demons",
    author: "Paula Guran",
    publisher: "Hachette UK",
    genre: "Fiction",
    isbnNo: 9781780338002,
    numofPages: 405,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 151,
    title: "The Eight",
    author: "Katherine Neville",
    publisher: "Open Road Media",
    genre: "Fiction",
    isbnNo: 9781504013673,
    numofPages: 523,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 152,
    title: "Angels, Demons and the New World",
    author: "Fernando Cervantes, Andrew Redden",
    publisher: "Cambridge University Press",
    genre: "Body, Mind & Spirit",
    isbnNo: 9780521764582,
    numofPages: 331,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 153,
    title: "Angels and Demons",
    author: "Ron Phillips",
    publisher: "Charisma Media",
    genre: "Body, Mind & Spirit",
    isbnNo: 9781629980348,
    numofPages: 289,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 154,
    title: "Angels And Demons",
    author: "Dan Brown",
    publisher: "Random House",
    genre: "Fiction",
    isbnNo: 9781409083948,
    numofPages: 663,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 155,
    title: "Secrets of Angels and Demons",
    author: "Daniel Burstein",
    publisher: "",
    genre: "Popes in literature",
    isbnNo: 9780752876931,
    numofPages: 595,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 156,
    title: "Angels, Demons & Gods of the New Millenium",
    author: "Lon Milo Duquette",
    publisher: "Weiser Books",
    genre: "Body, Mind & Spirit",
    isbnNo: 9781578630103,
    numofPages: 196,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 157,
    title: "Angels and Demons in Art",
    author: "Rosa Giorgi",
    publisher: "Getty Publications",
    genre: "Angels in art",
    isbnNo: 9780892368303,
    numofPages: 384,
    totalNumberOfCopies: 3,
    availableNumberOfCopies: 3,
  },
  {
    id: 158,
    title: "Demon Angel",
    author: "Meljean Brook",
    publisher: "Penguin",
    genre: "Fiction",
    isbnNo: 9781101568026,
    numofPages: 411,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 159,
    title: "Angels & Demons Rome",
    author: "Angela K. Nickerson",
    publisher: "Roaring Forties Press",
    genre: "Travel",
    isbnNo: 9780984316557,
    numofPages: 71,
    totalNumberOfCopies: 2,
    availableNumberOfCopies: 2,
  },
  {
    id: 160,
    title: "What Does the Bible Say About Angels and Demons?",
    author: "John Gillman, Clifford M. Yeary",
    publisher: "New City Press",
    genre: "Religion",
    isbnNo: 9781565483804,
    numofPages: 93,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 161,
    title: "The Sherlock Holmes Mysteries",
    author: "Sir Arthur Conan Doyle",
    publisher: "Penguin",
    genre: "Fiction",
    isbnNo: 9780698168237,
    numofPages: 546,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 162,
    title: "Demons & Angels",
    author: "J.K. Norry",
    publisher: "Sudden Insight Publishing",
    genre: "Fiction",
    isbnNo: 9780990728030,
    numofPages: 278,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 163,
    title: "A Brief History of Angels and Demons",
    author: "Sarah Bartlett",
    publisher: "Hachette UK",
    genre: "Body, Mind & Spirit",
    isbnNo: 9781849018289,
    numofPages: 164,
    totalNumberOfCopies: 5,
    availableNumberOfCopies: 5,
  },
  {
    id: 164,
    title: "Demons, Angels, and Writing in Ancient Judaism",
    author: "Annette Yoshiko Reed",
    publisher: "Cambridge University Press",
    genre: "Religion",
    isbnNo: 9780521119436,
    numofPages: 365,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 165,
    title: "An Angel, a Demon, a Candle",
    author: "Cordelia Faass",
    publisher: "Xlibris Corporation",
    genre: "Fiction",
    isbnNo: 9781479746750,
    numofPages: 99,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 166,
    title: "Sense and Nonsense about Angels and Demons",
    author: "Kenneth Boa, Robert M. Bowman Jr.",
    publisher: "Zondervan",
    genre: "Religion",
    isbnNo: 9780310254294,
    numofPages: 161,
    totalNumberOfCopies: 4,
    availableNumberOfCopies: 4,
  },
  {
    id: 167,
    title: "Origin",
    author: "Dan Brown",
    publisher: "Mizan Publishing",
    genre: "Fiction",
    isbnNo: 9786022914426,
    numofPages: 575,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 168,
    title: "Angels, Satan and Demons",
    author: "Robert Paul Lightner",
    publisher: "Thomas Nelson",
    genre: "Angels",
    isbnNo: 9780849913716,
    numofPages: 0,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 169,
    title: "The Truth About Angels and Demons",
    author: "Tony Evans",
    publisher: "Moody Publishers",
    genre: "Religion",
    isbnNo: 9781575677286,
    numofPages: 64,
    totalNumberOfCopies: 11,
    availableNumberOfCopies: 11,
  },
  {
    id: 170,
    title: "Angelfall",
    author: "Susan Ee",
    publisher: "Hachette UK",
    genre: "Fiction",
    isbnNo: 9781444778526,
    numofPages: 320,
    totalNumberOfCopies: 10,
    availableNumberOfCopies: 10,
  },
  {
    id: 171,
    title: "Deception Point",
    author: "Dan Brown",
    publisher: "Pocket Books",
    genre: "Fiction",
    isbnNo: 9781982122355,
    numofPages: 752,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 172,
    title: "The Magick of Angels and Demons",
    author: "Henry Archer",
    publisher: "Independently Published",
    genre: "Body, Mind & Spirit",
    isbnNo: 9781796703405,
    numofPages: 230,
    totalNumberOfCopies: 6,
    availableNumberOfCopies: 6,
  },
  {
    id: 173,
    title: "Angels, Demons, and the Devil",
    author: "F. Lagard Smith",
    publisher: "Cotswold Publishing",
    genre: "Religion",
    isbnNo: 9780966006063,
    numofPages: 254,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
  {
    id: 174,
    title: "The Language of Demons and Angels",
    author: "Christopher I. Lehrich",
    publisher: "BRILL",
    genre: "Body, Mind & Spirit",
    isbnNo: 9789004135741,
    numofPages: 276,
    totalNumberOfCopies: 8,
    availableNumberOfCopies: 8,
  },
  {
    id: 175,
    title: "Angels and Demons (Republish)",
    author: "Dan Brown",
    publisher: "Mizan Publishing",
    genre: "Fiction",
    isbnNo: 9786022914532,
    numofPages: 0,
    totalNumberOfCopies: 9,
    availableNumberOfCopies: 9,
  },
];
