import type { Metadata } from "next";
import "./globals.css";
import { EdgeStoreProvider } from "../lib/edgestore";
import { inter } from "@/components/ui/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`} 
      >
        {<EdgeStoreProvider>{children}</EdgeStoreProvider>}
      </body>
    </html>
  );
}
